[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[target.aarch64-apple-darwin]
# mold linker
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/bin/ld64.mold"]

[build]
rustc-wrapper = "~/.cargo/bin/sccache"

[profile.release]
strip = true
